name: safety
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  speech_to_text: ^2.3.0
  highlight_text: ^0.7.2
  quick_actions: ^0.5.0
  avatar_glow: ^1.2.0
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  path_provider: ^1.6.14
  video_player: ">=0.10.12+2 <2.0.0"
  youtube_player_flutter: ^7.0.0+7
  screen: ^0.0.5 # keeping screen on
  get_it: ^5.0.6
  provider: ^4.3.2
  hardware_buttons: ^1.0.0
  google_sign_in:
  flutter_ringtone_player: ^3.0.0
  wakelock: ^0.5.0+2
  flashlight: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  align_positioned: ^1.2.7

  hive: ^1.4.3
  maps_launcher: ^1.2.1
  url_launcher: ^5.0.3
  #  google_maps_flutter: ^0.5.30
  geolocator: ^5.3.2+2
  flutter_polyline_points: ^0.2.1
  gallery_saver: ^2.0.1
  image_picker: ^0.6.7+14
  sensors: ^0.4.2+4
  animated_widgets: ^1.0.6
  font_awesome_flutter: ^8.8.1
  flutter_open_whatsapp: ^0.1.2
  google_maps_cluster_manager: ^0.2.0
  camera: ^0.5.8+5
  path: ^1.7.0
  auto_size_text: ^2.1.0
  flash_animation: ^0.0.1
  simple_animations: ^2.2.1
  flutter_local_notifications: ^1.4.4+3
  introduction_screen: ^1.0.9
  json_serializable: ^3.3.0
  assets_audio_player: ^2.0.13
  flutter_sms: ^2.0.1+2
  #  flutter_facebook_login: ^3.0.0
  hexcolor: ^1.0.6
  flutter_zoom_drawer: ^1.0.4
  blobs: ^1.2.0
  circular_reveal_animation: ^1.1.5
  circle_list: ^1.0.4
  google_maps_flutter: ^1.0.5
  location: ^3.0.2
  animated_text_kit: ^1.3.0
  geocoder: ^0.2.1
  fancy_bottom_navigation: ^0.3.2
  esys_flutter_share: ^1.0.2
#  geolocator: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - music/
    - embed/
